[oauth-google]
  name         = "servant-oauth2-example-basic"
  callback_url = "http://localhost:8080/auth/google/complete"
  id           = "..."
  secret       = "..."

[oauth-github]
  name         = "servant-oauth2-example-basic"
  callback_url = "http://localhost:8080/auth/github/complete"
  id           = "..."
  secret       = "..."
