name:                servant-oauth2
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/tweag/servant-oauth2-combinator#readme
license:             BSD3
author:              Tweag
maintainer:          noon.vandersilk@tweag.io
copyright:           2022 Tweag
category:            Web
extra-source-files:
- README.md

ghc-options:
  -W
  -Wall

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - ImportQualifiedPost
  - KindSignatures
  - OverloadedStrings
  - PackageImports
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators

dependencies:
  - base >= 4.7 && < 5
  - base64-bytestring
  - binary
  - bytestring
  - clientsession
  - cookie
  - hoauth2
  - http-types
  - servant
  - servant-blaze
  - servant-server
  - shakespeare
  - text
  - tomland
  - uri-bytestring
  - wai
  - wai-middleware-auth
  - warp

executables:
  example-basic:
    source-dirs:      example-basic
    main:             Main.hs
    dependencies:
      - servant-oauth2

  example-cookies:
    source-dirs:      example-cookies
    main:             Main.hs
    dependencies:
      - servant-oauth2

library:
  source-dirs: src
