name:                servant-oauth2
version:             0.1.0.1
synopsis:            A library for OAuth2 authentication in servant.
description:
  A library for OAuth2 authentication in servant.

  It is a modern wrapper around wai-middleware-auth, and provides the ability
  to build type-safe authorised APIs with authentication provided by the wai
  oauth2 backends.

homepage:            https://github.com/tweag/servant-oauth2#readme
license:             MIT
license-file:        LICENSE
author:              Tweag
maintainer:          noon.vandersilk@tweag.io
copyright:           2022 Tweag
category:            Web
extra-source-files:
  - README.md
  - LICENSE

ghc-options:
  -W
  -Wall

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - ImportQualifiedPost
  - KindSignatures
  - OverloadedStrings
  - PackageImports
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators

dependencies:
  - base >= 4.7 && < 5
  - base64-bytestring
  - binary
  - bytestring
  - clientsession
  - cookie
  - exceptions
  - hoauth2
  - http-types
  - mtl
  - servant
  - servant-blaze
  - servant-server
  - shakespeare
  - text
  - tomland
  - unordered-containers
  - uri-bytestring
  - wai
  - wai-middleware-auth
  - warp

library:
  source-dirs: src
