name:                servant-oauth2-examples
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/tweag/servant-oauth2#readme
license:             BSD3
author:              Tweag
maintainer:          noon.vandersilk@tweag.io
copyright:           2022 Tweag
category:            Web
extra-source-files:
  - README.md
  - example-auth/db.txt


ghc-options:
  -W
  -Wall


default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - ImportQualifiedPost
  - KindSignatures
  - OverloadedStrings
  - PackageImports
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators


dependencies:
  - base >= 4.7 && < 5
  - base64-bytestring
  - binary
  - bytestring
  - clientsession
  - cookie
  - hoauth2
  - http-types
  - mtl
  - servant
  - servant-blaze
  - servant-oauth2
  - servant-server
  - shakespeare
  - text
  - tomland
  - unordered-containers
  - uri-bytestring
  - wai
  - wai-middleware-auth
  - warp


library:
  source-dirs: src


executables:
  example-simple:
    source-dirs:      example-simple
    main:             Main.hs
    dependencies:
      - servant-oauth2-examples

  example-cookies:
    source-dirs:      example-cookies
    main:             Main.hs
    dependencies:
      - servant-oauth2-examples

  example-auth:
    source-dirs:      example-auth
    main:             Main.hs
    dependencies:
      - servant-oauth2-examples


